//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerClubEntities : DbContext
    {
        public ComputerClubEntities()
            : base("name=ComputerClubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Cooler> Cooler { get; set; }
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<GameZone> GameZone { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<PlayPlaces> PlayPlaces { get; set; }
        public virtual DbSet<PowerUnit> PowerUnit { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Rols> Rols { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tariff> Tariff { get; set; }
    }
}
