//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerClub.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC()
        {
            this.GameZone = new HashSet<GameZone>();
        }
    
        public int ID_PC { get; set; }
        public int ID_Cooler { get; set; }
        public int ID_CPU { get; set; }
        public int ID_GPU { get; set; }
        public int ID_RAM { get; set; }
        public int ID_Motherboard { get; set; }
        public int ID_PowerUnit { get; set; }
    
        public virtual Cooler Cooler { get; set; }
        public virtual CPU CPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameZone> GameZone { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual PowerUnit PowerUnit { get; set; }
        public virtual RAM RAM { get; set; }
    }
}
